-- Read-only predecessor and compatible partial-install checks.
SELECT CASE WHEN
  (SELECT COUNT(*) FROM schema_migrations WHERE migration_name='2026-09-13-table-seating-v1' AND checksum='78f8798435bc6e44e45aeb1642189f42a9d562edb268354868b6d3e5a7674ab1')=1
  AND (SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='refunds' AND ENGINE='InnoDB')=1
  AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='refunds' AND COLUMN_NAME='invoice_id' AND DATA_TYPE='int' AND COLUMN_TYPE NOT LIKE '%unsigned%')=1
  AND (SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE k JOIN information_schema.REFERENTIAL_CONSTRAINTS r
    ON r.CONSTRAINT_SCHEMA=k.CONSTRAINT_SCHEMA AND r.TABLE_NAME=k.TABLE_NAME AND r.CONSTRAINT_NAME=k.CONSTRAINT_NAME
    WHERE k.CONSTRAINT_SCHEMA=DATABASE() AND k.TABLE_NAME='refunds' AND k.CONSTRAINT_NAME='fk_refunds_invoice'
      AND k.COLUMN_NAME='invoice_id' AND k.REFERENCED_TABLE_NAME='orders' AND k.REFERENCED_COLUMN_NAME='invoice_id' AND r.DELETE_RULE='CASCADE')=1
  AND (NOT EXISTS (SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='deleted') OR (
    (SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='deleted' AND ENGINE='InnoDB')=1
    AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='deleted')=10
    AND (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='deleted' AND (
      (COLUMN_NAME='id' AND DATA_TYPE='bigint' AND COLUMN_TYPE LIKE '%unsigned%' AND EXTRA LIKE '%auto_increment%') OR
      (COLUMN_NAME IN ('refund_id','source_invoice_id','source_order_item_id') AND DATA_TYPE='int' AND COLUMN_TYPE NOT LIKE '%unsigned%' AND IS_NULLABLE='NO') OR
      (COLUMN_NAME IN ('source_parent_item_id','product_id') AND DATA_TYPE='int' AND COLUMN_TYPE NOT LIKE '%unsigned%' AND IS_NULLABLE='YES') OR
      (COLUMN_NAME='item_name' AND DATA_TYPE='varchar' AND CHARACTER_MAXIMUM_LENGTH=255) OR
      (COLUMN_NAME='quantity' AND DATA_TYPE='decimal' AND NUMERIC_PRECISION=12 AND NUMERIC_SCALE=6 AND IS_NULLABLE='NO') OR
      (COLUMN_NAME='item_snapshot' AND DATA_TYPE IN ('json','longtext') AND IS_NULLABLE='NO') OR
      (COLUMN_NAME='created_at' AND DATA_TYPE='timestamp' AND IS_NULLABLE='NO')))=10
    AND (SELECT COUNT(*) FROM (SELECT INDEX_NAME FROM information_schema.STATISTICS
      WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='deleted' AND INDEX_NAME='uq_deleted_event_item'
      GROUP BY INDEX_NAME HAVING COUNT(*)=2 AND MIN(NON_UNIQUE)=0 AND MAX(NON_UNIQUE)=0 AND SUM(SUB_PART IS NOT NULL)=0
        AND GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX)='refund_id,source_order_item_id') event_keys)=1
    AND (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='deleted'
      AND INDEX_NAME='idx_deleted_source_invoice' AND COLUMN_NAME='source_invoice_id' AND NON_UNIQUE=1 AND SUB_PART IS NULL)=1
    AND (SELECT COUNT(*) FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE()
      AND TABLE_NAME='deleted' AND CONSTRAINT_NAME='fk_deleted_refund' AND REFERENCED_TABLE_NAME='refunds' AND DELETE_RULE='CASCADE')=1
    AND (SELECT COUNT(*) FROM information_schema.CHECK_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE()
      AND TABLE_NAME='deleted' AND CONSTRAINT_NAME='chk_deleted_quantity')=1
  ))
THEN 1 ELSE 0 END AS ok;
