ALTER TABLE print_queue
  MODIFY status enum('pending','processing','sent','acknowledged','failed','dead_letter','canceled') NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS idempotency_key varchar(160) DEFAULT NULL AFTER id,
  ADD COLUMN IF NOT EXISTS payload_hash char(64) DEFAULT NULL AFTER payload,
  ADD COLUMN IF NOT EXISTS printer_id varchar(128) DEFAULT NULL AFTER payload_hash,
  ADD COLUMN IF NOT EXISTS print_type varchar(64) DEFAULT NULL AFTER printer_id,
  ADD COLUMN IF NOT EXISTS spooler_id varchar(128) DEFAULT NULL AFTER claimed_by,
  ADD COLUMN IF NOT EXISTS spooler_version varchar(64) DEFAULT NULL AFTER spooler_id,
  ADD COLUMN IF NOT EXISTS max_attempts int(11) NOT NULL DEFAULT 5 AFTER attempts,
  ADD COLUMN IF NOT EXISTS first_attempt_at datetime DEFAULT NULL AFTER max_attempts,
  ADD COLUMN IF NOT EXISTS device_status enum('unknown','ok','offline','paper_low','paper_out','cover_open','jammed','error') NOT NULL DEFAULT 'unknown' AFTER last_error,
  ADD COLUMN IF NOT EXISTS sent_at datetime DEFAULT NULL AFTER first_attempt_at,
  ADD COLUMN IF NOT EXISTS acknowledged_at datetime DEFAULT NULL AFTER sent_at,
  ADD COLUMN IF NOT EXISTS duration_ms int(11) DEFAULT NULL AFTER acknowledged_at,
  ADD COLUMN IF NOT EXISTS next_retry_at datetime DEFAULT NULL AFTER duration_ms,
  ADD COLUMN IF NOT EXISTS reprint_of_queue_id bigint(20) DEFAULT NULL AFTER next_retry_at,
  ADD COLUMN IF NOT EXISTS last_seen_at datetime DEFAULT NULL AFTER reprint_of_queue_id,
  ADD UNIQUE KEY IF NOT EXISTS uq_print_queue_idempotency (idempotency_key),
  ADD KEY IF NOT EXISTS idx_print_queue_state_locked (status, locked_until),
  ADD KEY IF NOT EXISTS idx_print_queue_state_created (status, created_at),
  ADD KEY IF NOT EXISTS idx_print_queue_reprint_of (reprint_of_queue_id);
