-- 2026-09-12-stock-item-identity-v1
-- One balance per item. Retained nullable warehouse IDs are historical provenance.
-- Run with application writers stopped. Unsupported warehouse data fails before DDL.
SET @stock_identity_ok = 1;
SET @stock_identity_sql = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='stock_lots'),'SELECT @stock_identity_ok := @stock_identity_ok AND NOT EXISTS(SELECT 1 FROM stock_lots WHERE is_default<>1 OR lot_code<>''default'' OR state<>''eligible'' OR expiry_date IS NOT NULL)','SELECT 1');
PREPARE stock_identity_stmt FROM @stock_identity_sql;
EXECUTE stock_identity_stmt;
DEALLOCATE PREPARE stock_identity_stmt;
SET @stock_identity_sql = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='stock_locations'),'SELECT @stock_identity_ok := @stock_identity_ok AND NOT EXISTS(SELECT 1 FROM stock_balances b JOIN stock_locations l ON l.id=b.location_id WHERE l.code<>''default'' OR l.is_active<>1)','SELECT 1');
PREPARE stock_identity_stmt FROM @stock_identity_sql;
EXECUTE stock_identity_stmt;
DEALLOCATE PREPARE stock_identity_stmt;
SET @stock_identity_sql = IF(1,'SELECT @stock_identity_ok := @stock_identity_ok AND NOT EXISTS(SELECT stock_item_id FROM stock_balances GROUP BY stock_item_id HAVING COUNT(*)>1)','SELECT 1');
PREPARE stock_identity_stmt FROM @stock_identity_sql;
EXECUTE stock_identity_stmt;
DEALLOCATE PREPARE stock_identity_stmt;
SET @stock_identity_sql = IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='stock_items' AND COLUMN_NAME='lot_required'),'SELECT @stock_identity_ok := @stock_identity_ok AND NOT EXISTS(SELECT 1 FROM stock_items WHERE lot_required<>0)','SELECT 1');
PREPARE stock_identity_stmt FROM @stock_identity_sql;
EXECUTE stock_identity_stmt;
DEALLOCATE PREPARE stock_identity_stmt;
SET @stock_identity_sql = IF(@stock_identity_ok=1,'SELECT 1','SELECT * FROM posapp_stock_identity_requires_review');
PREPARE stock_identity_stmt FROM @stock_identity_sql;
EXECUTE stock_identity_stmt;
DEALLOCATE PREPARE stock_identity_stmt;
SET @stock_identity_sql = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='stock_receipt_lines'),'ALTER TABLE stock_receipt_lines ADD COLUMN IF NOT EXISTS legacy_stock_identity JSON DEFAULT NULL','SELECT 1');
PREPARE stock_identity_stmt FROM @stock_identity_sql;
EXECUTE stock_identity_stmt;
DEALLOCATE PREPARE stock_identity_stmt;
SET @stock_identity_sql = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='stock_receipt_lines') AND EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='stock_locations') AND EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='stock_lots'),'UPDATE stock_receipt_lines r JOIN stock_locations l ON l.id=r.location_id JOIN stock_lots t ON t.id=r.lot_id SET r.legacy_stock_identity=JSON_OBJECT(''location_id'',CAST(l.id AS CHAR),''location_code'',l.code,''location_name'',l.name,''location_active'',l.is_active,''lot_id'',CAST(t.id AS CHAR),''lot_code'',t.lot_code,''expiry_date'',t.expiry_date,''state'',t.state,''is_default'',t.is_default) WHERE r.legacy_stock_identity IS NULL','SELECT 1');
PREPARE stock_identity_stmt FROM @stock_identity_sql;
EXECUTE stock_identity_stmt;
DEALLOCATE PREPARE stock_identity_stmt;
SET @stock_identity_sql = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='stock_receipt_lines'),'ALTER TABLE stock_receipt_lines DROP FOREIGN KEY IF EXISTS fk_stock_receipt_line_location','SELECT 1');
PREPARE stock_identity_stmt FROM @stock_identity_sql;
EXECUTE stock_identity_stmt;
DEALLOCATE PREPARE stock_identity_stmt;
SET @stock_identity_sql = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='stock_receipt_lines'),'ALTER TABLE stock_receipt_lines DROP FOREIGN KEY IF EXISTS fk_stock_receipt_line_lot','SELECT 1');
PREPARE stock_identity_stmt FROM @stock_identity_sql;
EXECUTE stock_identity_stmt;
DEALLOCATE PREPARE stock_identity_stmt;
ALTER TABLE stock_movements DROP FOREIGN KEY IF EXISTS fk_stock_movement_balance;
ALTER TABLE stock_balances DROP FOREIGN KEY IF EXISTS fk_stock_balance_location;
ALTER TABLE stock_balances DROP FOREIGN KEY IF EXISTS fk_stock_balance_lot;
SET @stock_identity_sql = IF((SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='stock_balances' AND INDEX_NAME='PRIMARY') <> 'stock_item_id','ALTER TABLE stock_balances DROP PRIMARY KEY, ADD PRIMARY KEY(stock_item_id)','SELECT 1');
PREPARE stock_identity_stmt FROM @stock_identity_sql;
EXECUTE stock_identity_stmt;
DEALLOCATE PREPARE stock_identity_stmt;
ALTER TABLE stock_balances MODIFY COLUMN location_id BIGINT UNSIGNED NULL DEFAULT NULL, MODIFY COLUMN lot_id BIGINT UNSIGNED NULL DEFAULT NULL;
ALTER TABLE stock_balances DROP INDEX IF EXISTS idx_stock_balance_location, DROP INDEX IF EXISTS fk_stock_balance_lot;
ALTER TABLE stock_movements MODIFY COLUMN location_id BIGINT UNSIGNED NULL DEFAULT NULL, MODIFY COLUMN lot_id BIGINT UNSIGNED NULL DEFAULT NULL;
ALTER TABLE stock_movements DROP INDEX IF EXISTS idx_stock_movement_history;
CREATE INDEX IF NOT EXISTS idx_stock_movement_history ON stock_movements(stock_item_id,id);
SET @stock_identity_sql = IF(NOT EXISTS(SELECT 1 FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND CONSTRAINT_NAME='fk_stock_movement_balance'),'ALTER TABLE stock_movements ADD CONSTRAINT fk_stock_movement_balance FOREIGN KEY(stock_item_id) REFERENCES stock_balances(stock_item_id)','SELECT 1');
PREPARE stock_identity_stmt FROM @stock_identity_sql;
EXECUTE stock_identity_stmt;
DEALLOCATE PREPARE stock_identity_stmt;
DROP TABLE IF EXISTS stock_lots;
DROP TABLE IF EXISTS stock_locations;
ALTER TABLE stock_items DROP CONSTRAINT IF EXISTS ck_stock_item_flags;
ALTER TABLE stock_items DROP COLUMN IF EXISTS lot_required;
ALTER TABLE stock_items ADD CONSTRAINT ck_stock_item_flags CHECK (is_active IN (0,1));
INSERT INTO schema_migrations(migration_name,checksum) VALUES ('2026-09-12-stock-item-identity-v1','045d0475fd16715e4eafb913a6f7fe839ed7fb7920e2a8d478b86878172de24b')
ON DUPLICATE KEY UPDATE migration_name=VALUES(migration_name);
