// @/pos/useCart.js — logic-free facade over the order stores.
// State + logic live in stores/orderSessionStore.js and stores/orderUiStore.js.
// This file ONLY renames/re-exports. Do not add branches or derivations here.
import { storeToRefs } from 'pinia';
import { useRouter } from 'vue-router';
import { useOrderSessionStore } from './stores/orderSessionStore.js';
import { useOrderUiStore } from './stores/orderUiStore.js';

export function useCart() {
  const session = useOrderSessionStore();
  const ui = useOrderUiStore();
  const s = storeToRefs(session);
  const u = storeToRefs(ui);
  const router = typeof useRouter === 'function' ? useRouter() : null;

  return {
    // session state + getters (refs)
    cart: s.cart,
    selectedCartIndex: s.selectedCartIndex,
    orderNote: s.orderNote,
    orderDiscount: s.orderDiscount,
    orderTypes: s.orderTypes,
    selectedOrderType: s.selectedOrderType,
    customerPhone: s.customerPhone,
    customerName: s.customerName,
    customerAddress: s.customerAddress,
    orderDate: s.orderDate,
    hashNumber: s.hashNumber,
    restoredHeldReference: s.restoredHeldReference,
    restoredHeldOrder: s.restoredHeldOrder,
    callCenterSession: s.callCenterSession,
    isCallCenter: s.isCallCenter,
    callCenterCommands: s.callCenterCommands,
    courses: s.courses,
    taxInclusivePricing: s.taxInclusivePricing,
    receiptTaxInclusiveDisplay: s.receiptTaxInclusiveDisplay,
    isTaxExempt: s.isTaxExempt,
    taxRegistrationType: s.taxRegistrationType,
    guestCheckInFlight: s.guestCheckInFlight,
    canTaxExempt: s.canTaxExempt,
    cartSubtotal: s.cartSubtotal,
    cartOrderDiscountAmount: s.cartOrderDiscountAmount,
    cartTax: s.cartTax,
    cartTotal: s.cartTotal,
    cartReceiptPresentation: s.cartReceiptPresentation,
    changeDue: s.changeDue,
    cashShortfall: s.cashShortfall,
    splitBalanceDue: s.splitBalanceDue,
    selectedOrderTypeRequiresHash: s.selectedOrderTypeRequiresHash,
    isDirectPlatformCheckout: s.isDirectPlatformCheckout,
    defaultOrderTypeId: s.defaultOrderTypeId,
    serviceChargeEnabled: s.serviceChargeEnabled,
    serviceChargePercentage: s.serviceChargePercentage,
    autoApplyServiceCharge: s.autoApplyServiceCharge,
    canRemoveAutoServiceCharge: s.canRemoveAutoServiceCharge,
    canApplyDiscount: s.canApplyDiscount,
    canVoidActiveTable: s.canVoidActiveTable,
    hasSavedTableItems: s.hasSavedTableItems,
    canRemoveSelectedCartItem: s.canRemoveSelectedCartItem,
    canClearCart: s.canClearCart,
    canApplyServiceCharge: s.canApplyServiceCharge,
    canCheckout: s.canCheckout,
    canCheckoutTable: s.canCheckoutTable,
    canPrintCheck: s.canPrintCheck,

    // ui state (refs)
    showCheckoutModal: u.showCheckoutModal,
    paymentMethod: u.paymentMethod,
    amountTendered: u.amountTendered,
    splitCardAmount: u.splitCardAmount,
    splitCashTendered: u.splitCashTendered,
    isProcessing: u.isProcessing,
    checkoutInFlight: s.checkoutInFlight,
    pendingCheckout: s.pendingCheckout,
    pendingCheckoutUnreadable: s.pendingCheckoutUnreadable,
    canDiscardPendingCheckout: s.canDiscardPendingCheckout,
    isHolding: u.isHolding,
    checkoutError: u.checkoutError,
    numpadInput: u.numpadInput,
    numpadMode: u.numpadMode,
    quickTargetAmount: u.quickTargetAmount,
    mobileCartOpen: u.mobileCartOpen,
    showCustomerDrawer: u.showCustomerDrawer,
    activeModal: u.activeModal,
    modalTarget: u.modalTarget,
    tempNote: u.tempNote,
    tempDiscount: u.tempDiscount,
    isCustomerLoading: u.isCustomerLoading,
    showModifierModal: u.showModifierModal,
    activeModifierProduct: u.activeModifierProduct,
    selectedModifiers: u.selectedModifiers,
    showCourseModal: u.showCourseModal,
    showMoreActionsModal: u.showMoreActionsModal,
    activeIdempotencyKey: u.activeIdempotencyKey,

    // actions (functions — passthrough, NOT via storeToRefs)
    getItemTotalGross: session.getItemTotalGross,
    startNewOrder: session.startNewOrder,
    loadSavedOrder: session.loadSavedOrder,
    loadOrderForEditing: session.loadOrderForEditing,
    // Only allowed wrappers: bind the component router so table exits stay in the SPA.
    clearCart: (opts) => session.clearCart({ skipConfirm: opts?.skipConfirm === true, router }),
    removeSelectedCartItem: () => session.removeSelectedCartItem({ router }),
    restoreHeldOrder: session.restoreHeldOrder,
    markServerCanonicalRestore: session.markServerCanonicalRestore,
    consumeServerCanonicalRestore: session.consumeServerCanonicalRestore,
    markLocalFallbackRestore: session.markLocalFallbackRestore,
    consumeRestoreSource: session.consumeRestoreSource,
    initializeCallCenterSession: session.initializeCallCenterSession,
    startCallCenterOrder: session.startCallCenterOrder,
    findCallCenterOrders: session.findCallCenterOrders,
    continueCallCenterOrder: session.continueCallCenterOrder,
    reconnectHeldOrder: session.reconnectHeldOrder,
    sendCallCenterOrder: session.sendCallCenterOrder,
    cancelCallCenterEdits: session.cancelCallCenterEdits,
    cancelCallCenterOrder: session.cancelCallCenterOrder,
    sendHeldOrderFollowUp: session.sendHeldOrderFollowUp,
    confirmHeldKitchenBaseline: session.confirmHeldKitchenBaseline,
    claimHeldOrderForHandoff: session.claimHeldOrderForHandoff,
    getHeldOrdersSummary: session.getHeldOrdersSummary,
    setNumpadMode: ui.setNumpadMode,
    appendNumpad: session.appendNumpad,
    clearNumpad: session.clearNumpad,
    backspaceNumpad: session.backspaceNumpad,
    armQuickAmount: session.armQuickAmount,
    cancelQuickAmount: session.cancelQuickAmount,
    applyQuantityPreset: session.applyQuantityPreset,
    importQrDraftItems: session.importQrDraftItems,
    addToCart: session.addToCart,
    toggleModifier: session.toggleModifier,
    confirmModifiers: session.confirmModifiers,
    cancelModifiers: session.cancelModifiers,
    openNoteModal: session.openNoteModal,
    saveNote: session.saveNote,
    openDiscountModal: session.openDiscountModal,
    saveDiscount: session.saveDiscount,
    clearDiscount: session.clearDiscount,
    openCheckoutModal: session.openCheckoutModal,
    closeCheckoutModal: ui.closeCheckoutModal,
    processCheckout: () => session.processCheckout({ router }),
    probePendingCheckout: (opts) => session.probePendingCheckout({ heartbeat: opts?.heartbeat === true, router }),
    discardPendingCheckout: session.discardPendingCheckout,
    dismissPendingCheckoutUnreadable: session.dismissPendingCheckoutUnreadable,
    openCashDrawer: session.openCashDrawer,
    fetchOrderTypes: session.fetchOrderTypes,
    lookupCustomer: session.lookupCustomer,
    printGuestCheck: session.printGuestCheck,
    addServiceCharge: session.addServiceCharge,
    removeAutoServiceCharge: session.removeAutoServiceCharge,
    toggleTaxExempt: session.toggleTaxExempt,
    setItemCourse: session.setItemCourse,
    clearItemCourse: session.clearItemCourse,
    getQtyInCart: session.getQtyInCart,
    getPendingQtyInCart: session.getPendingQtyInCart,
    captureOrderSession: session.captureOrderSession,
    isCurrentOrderSession: session.isCurrentOrderSession,
    handleOrderTypeSelection: session.handleOrderTypeSelection,
    syncCheckoutPaymentForOrderType: session.syncCheckoutPaymentForOrderType,
  };
}
